[package]
name = "lacker"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.9"
gtk4-layer-shell = {version = "0.4", optional = true}
freedesktop-desktop-entry = "0.5"
chrono = "0.4"

[features]
default = []
wayland = ["gtk4-layer-shell"]
